# -*- coding: utf-8 -*-
"""perceprton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lL1495Cxq-Ef2tLGbOw2_3rzAtaL9qvI
"""

from numpy import array, dot, random
from random import choice

def hardlim(val):
    if (val < 0):
        return 0
    else:
        return 1

#tanitasi halmaz
d = [
     (array([1,0,0]), 0),
     (array([1,0,1]), 0),
     (array([1,1,0]), 0),
     (array([1,1,1]), 1),
]

#tanulas merteke
lr = 0.1

#sulyzok
w = random.rand(3)

#hany cikluson menjen vegig a tanulas 
n=100

#szamlalo a ciklusbol valo kilepeshez
E = 1

while E != 0:
    E = 0
    for i in range(n):
        x, di = choice(d)
        yi = dot(w, x)
        ei = di - hardlim(yi)
        w = w + (lr * ei *x)
        E = E + (ei **2)
        print("AND {}: {} -> {}".format(x[1:3], yi, hardlim(yi)))
        print(w)
        print("\n")